FROM alpine:3.10.0

#RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.aliyun.com/g' /etc/apk/repositories;

RUN apk update && apk upgrade
RUN apk add squid \
            bash;

WORKDIR /root

RUN sed -i 's/http_access deny all/http_access allow all/g' /etc/squid/squid.conf;

EXPOSE 3128
CMD ["squid", "-N"]
